package com.arklight.app

import android.Manifest
import android.content.pm.PackageManager
import android.os.Build
import android.os.Bundle
import android.webkit.WebResourceRequest
import android.webkit.WebResourceResponse
import android.webkit.WebView
import android.webkit.WebViewClient
import androidx.activity.result.contract.ActivityResultContracts
import androidx.appcompat.app.AlertDialog
import androidx.appcompat.app.AppCompatActivity
import androidx.core.content.ContextCompat
import androidx.webkit.WebViewAssetLoader

/**
 * Application-mode runtime shell, generated by `arklight android scaffold`, then
 * hand-extended here with a Bluetooth HID Device peripheral: the WebView renders
 * the remote's UI; BtHidManager owns the actual Classic-BT HID profile connection
 * and report sending; WebAppBridge is the narrow JS<->native seam between them.
 */
class MainActivity : AppCompatActivity() {

    private lateinit var webView: WebView
    private lateinit var hidManager: BtHidManager

    private val requestBtPermission = registerForActivityResult(
        ActivityResultContracts.RequestPermission()
    ) { granted -> if (granted) startHid() else notifyPage("permission_denied") }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        webView = WebView(this)
        setContentView(webView)

        webView.settings.javaScriptEnabled = true
        webView.settings.domStorageEnabled = true

        hidManager = BtHidManager(this)
        webView.addJavascriptInterface(WebAppBridge(this, hidManager), "AndroidBridge")

        val assetLoader = WebViewAssetLoader.Builder()
            .addPathHandler("/assets/", WebViewAssetLoader.AssetsPathHandler(this))
            .build()

        webView.webViewClient = object : WebViewClient() {
            override fun shouldInterceptRequest(
                view: WebView,
                request: WebResourceRequest
            ): WebResourceResponse? = assetLoader.shouldInterceptRequest(request.url)
        }

        webView.loadUrl(SITE_URL)
        ensureBtPermissionThenStart()
    }

    private fun ensureBtPermissionThenStart() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
            val granted = ContextCompat.checkSelfPermission(
                this, Manifest.permission.BLUETOOTH_CONNECT
            ) == PackageManager.PERMISSION_GRANTED
            if (granted) startHid() else requestBtPermission.launch(Manifest.permission.BLUETOOTH_CONNECT)
        } else {
            startHid() // pre-API31: BLUETOOTH/BLUETOOTH_ADMIN are install-time, no prompt needed
        }
    }

    private fun startHid() {
        // Once the SDP record is registered, opportunistically try every bonded
        // device -- see BtHidManager.autoConnectBonded() for why this is a "try
        // them all" approach rather than picking exactly one.
        hidManager.onStateChanged = { state ->
            notifyPage(state)
            if (state == "registered") hidManager.autoConnectBonded()
        }
        hidManager.start()
    }

    /** Native single-choice picker: every entry in MappingStore.ASSIGNABLE, current
     *  assignment pre-selected. Selecting one persists it and updates the page. */
    fun showMapper(buttonId: String) {
        val options = MappingStore.ASSIGNABLE
        val current = MappingStore.get(this, buttonId)
        val checkedIndex = options.indexOfFirst { it.kind == current.kind && it.usage == current.usage }
        val labels = options.map { t ->
            (if (t.kind == HidKind.CONSUMER) "Consumer: " else "Key: ") + t.label
        }.toTypedArray()

        AlertDialog.Builder(this)
            .setTitle("Map \"$buttonId\" to…")
            .setSingleChoiceItems(labels, checkedIndex) { dialog, which ->
                val target = options[which]
                MappingStore.set(this, buttonId, target)
                notifyRemap(buttonId, target.label)
                dialog.dismiss()
            }
            .setNeutralButton("Reset to default") { _, _ ->
                MappingStore.resetOne(this, buttonId)
                notifyRemap(buttonId, MappingStore.get(this, buttonId).label)
            }
            .setNegativeButton("Cancel", null)
            .show()
    }

    private fun notifyRemap(buttonId: String, label: String) {
        runOnUiThread {
            webView.evaluateJavascript(
                "window.onRemapped && window.onRemapped(${org.json.JSONObject.quote(buttonId)}, ${org.json.JSONObject.quote(label)});",
                null,
            )
        }
    }

    /** Push connection-state events into the page so the UI can reflect them. */
    private fun notifyPage(state: String) {
        runOnUiThread {
            webView.evaluateJavascript(
                "window.onHidState && window.onHidState(${org.json.JSONObject.quote(state)});",
                null,
            )
        }
    }

    @Suppress("DEPRECATION")
    override fun onBackPressed() {
        if (webView.canGoBack()) webView.goBack() else super.onBackPressed()
    }

    companion object {
        private const val SITE_URL = "https://appassets.androidplatform.net/assets/index.html"
    }
}
